// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateUploadRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    contentType: string;
    purpose: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type QueryParameter = {
    Name: string;
    Value: Array<string> | null;
};

export type UpdateUserRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UpdateUserRoleRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    role: string;
};

export type UploadUrls = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Where the file will be reachable once the upload completes
     */
    publicUrl: string;
    /**
     * PUT the file here directly, with the same Content-Type used to request this URL
     */
    uploadUrl: string;
};

export type UserPrivateProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    role: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfile = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type CreateUploadRequestWritable = {
    contentType: string;
    purpose: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type UpdateUserRequestWritable = {
    bio?: string;
    email?: string;
    profilePicture?: string;
    timezone?: string;
    username?: string;
};

export type UpdateUserRoleRequestWritable = {
    role: string;
};

export type UploadUrlsWritable = {
    /**
     * Where the file will be reachable once the upload completes
     */
    publicUrl: string;
    /**
     * PUT the file here directly, with the same Content-Type used to request this URL
     */
    uploadUrl: string;
};

export type UserPrivateProfileWritable = {
    bio?: string;
    createdAt: string;
    email: string;
    emailVerified: boolean;
    id: string;
    profilePicture?: string;
    role: string;
    timezone?: string;
    updatedAt: string;
    username: string;
};

export type UserPublicProfileWritable = {
    bio?: string;
    createdAt: string;
    id: string;
    profilePicture?: string;
    username: string;
};

export type GetDatabaseHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/health';
};

export type GetDatabaseHealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDatabaseHealthError = GetDatabaseHealthErrors[keyof GetDatabaseHealthErrors];

export type GetDatabaseHealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDatabaseHealthResponse = GetDatabaseHealthResponses[keyof GetDatabaseHealthResponses];

export type PostDatabaseMigrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/database/migrations';
};

export type PostDatabaseMigrationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostDatabaseMigrationsError = PostDatabaseMigrationsErrors[keyof PostDatabaseMigrationsErrors];

export type PostDatabaseMigrationsResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostDatabaseMigrationsResponse = PostDatabaseMigrationsResponses[keyof PostDatabaseMigrationsResponses];

export type PostUploadsData = {
    body: CreateUploadRequestWritable;
    path?: never;
    query?: never;
    url: '/uploads';
};

export type PostUploadsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUploadsError = PostUploadsErrors[keyof PostUploadsErrors];

export type PostUploadsResponses = {
    /**
     * OK
     */
    200: UploadUrls;
};

export type PostUploadsResponse = PostUploadsResponses[keyof PostUploadsResponses];

export type DeleteUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteUsersMeError = DeleteUsersMeErrors[keyof DeleteUsersMeErrors];

export type DeleteUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type DeleteUsersMeResponse = DeleteUsersMeResponses[keyof DeleteUsersMeResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: UpdateUserRequestWritable;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type PostUsersSearchData = {
    body: Array<QueryParameter> | null;
    path?: never;
    query?: never;
    url: '/users/search';
};

export type PostUsersSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUsersSearchError = PostUsersSearchErrors[keyof PostUsersSearchErrors];

export type PostUsersSearchResponses = {
    /**
     * OK
     */
    200: Array<UserPublicProfile> | null;
};

export type PostUsersSearchResponse = PostUsersSearchResponses[keyof PostUsersSearchResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * OK
     */
    200: UserPublicProfile;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PatchUsersByIdRoleData = {
    body: UpdateUserRoleRequestWritable;
    path: {
        /**
         * ID (UUID) of the user whose role is being changed
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/role';
};

export type PatchUsersByIdRoleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PatchUsersByIdRoleError = PatchUsersByIdRoleErrors[keyof PatchUsersByIdRoleErrors];

export type PatchUsersByIdRoleResponses = {
    /**
     * OK
     */
    200: UserPrivateProfile;
};

export type PatchUsersByIdRoleResponse = PatchUsersByIdRoleResponses[keyof PatchUsersByIdRoleResponses];
